### ISSUE TITLE
`public_key': undefined method `code' for #<Errno::ECONNREFUSED:0x000000031e9440> (NoMethodError)

### ISSUE THREAD

**Issue by RickCarlino** [FarmBot/farmbot-resource#2]
```
/home/rick/.rvm/gems/ruby-2.2.3/gems/farmbot-resource-0.6.0/lib/client.rb:36:in `public_key': undefined method `code' for #<Errno::ECONNREFUSED:0x000000031e9440> (NoMethodError)
	from /home/rick/code/farmbot/rpi-controller/lib/rest_client.rb:18:in `initialize'
	from /home/rick/code/farmbot/rpi-controller/lib/farmbot-pi.rb:20:in `new'
	from /home/rick/code/farmbot/rpi-controller/lib/farmbot-pi.rb:20:in `initialize'
	from farmbot.rb:4:in `new'
	from farmbot.rb:4:in `<main>'
```

**Comment by RickCarlino** [comment]
Will get to this one later. Leave a comment if you need it sooner.

The TL;DR of it is that you will see this if the bot's web server (usually `my.farmbot.io`) is down. That's uncommon, which is why I am placing this into my "low priority" pile.
